"""
Script Generation Agent - Converts test cases into executable Playwright Python scripts with error recovery patching
"""
import json
from state import AgentState
from .base_agent import BaseAgent
from typing import List, Dict, Any, Optional

class ScriptGenerationAgent(BaseAgent):
    def __init__(self, model_client=None):
        super().__init__("Script_Generation", model_client)

    async def invoke(self, state: AgentState) -> AgentState:
        self.log_start("Generating executable Playwright Python scripts...")
        approved_tcs = state.get("approved_test_cases", state.get("test_cases", []))
        target_url = state.get("target_url", self.config.TARGET_URL)
        retry_count = state.get("retry_count", 0)
        last_error = state.get("last_error", None)
        error_analysis = state.get("error_analysis", None)

        if not approved_tcs:
            self.log_error("No approved test cases available for script generation")
            return state

        # Focus on active test case or compile main execution script
        if retry_count > 0 and last_error:
            self.log_info(f"🔄 Regenerating script for Retry #{retry_count} using failure analysis feedback...")

        tc_summary = json.dumps(approved_tcs, indent=2)
        error_context = ""
        if error_analysis:
            error_context = f"""
PREVIOUS EXECUTION FAILURE CONTEXT (RETRY #{retry_count}):
Last Error Message: {last_error}
Failure Cause: {error_analysis.get('root_cause', 'Unknown')}
Suggested Patch Strategy: {error_analysis.get('corrective_action', 'Update locators and add explicit wait conditions')}
Recommended Locators/Code Fixes: {error_analysis.get('patch_code', '')}
"""

        prompt = f"""Generate a clean, executable Python script using Playwright async API to execute these test cases against: {target_url}

Approved Test Cases:
{tc_summary}
{error_context}

REQUIREMENTS FOR GENERATED PLAYWRIGHT SCRIPT:
1. Must be complete, runnable Python code with imports: `asyncio`, `playwright.async_api`.
2. Must run in headless mode: `headless={str(self.config.HEADLESS).lower()}`.
3. Must use resilient selector strategies (e.g. `page.get_by_role`, `page.locator`, text fallbacks).
4. Must include explicit assertions and exception handling.
5. On completion or error, print a final JSON status line:
   `JSON_RESULT: {{"status": "PASSED"}}` or `JSON_RESULT: {{"status": "FAILED", "error": "..."}}`
6. Save failure screenshots if an assertion or navigation fails.

Return ONLY valid executable Python code in ```python ... ``` block:"""

        def _mock_script_generator() -> str:
            # Standalone robust Playwright test script
            return f'''"""
Playwright Automation Script - Generated by Agentic QA Framework
Target: {target_url}
"""
import asyncio
import os
import sys
import json
from playwright.async_api import async_playwright

async def run_tests():
    target_url = "{target_url}"
    headless = {str(self.config.HEADLESS)}
    print(f"🚀 Starting Playwright test execution against {{target_url}}...")
    
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=headless)
        context = await browser.new_context(viewport={{"width": 1280, "height": 720}})
        page = await context.new_page()
        
        try:
            # Step 1: Navigate to target URL
            print(f"Navigating to {{target_url}}...")
            response = await page.goto(target_url, timeout={self.config.TIMEOUT}, wait_until="domcontentloaded")
            
            # Verify status code if available
            if response and response.status >= 400:
                raise RuntimeError(f"HTTP Error {{response.status}} loading page {{target_url}}")
                
            await page.wait_for_timeout(1000)
            
            # Step 2: Verify page title or body exists
            title = await page.title()
            print(f"Page loaded successfully. Title: '{{title}}'")
            
            # Save proof screenshot
            os.makedirs("logs", exist_ok=True)
            screenshot_path = os.path.join("logs", "execution_success.png")
            await page.screenshot(path=screenshot_path)
            print(f"📸 Screenshot saved to {{screenshot_path}}")
            
            await browser.close()
            print('JSON_RESULT: {{"status": "PASSED", "message": "All test assertions passed successfully"}}')
            return True
            
        except Exception as e:
            error_msg = str(e)
            print(f"❌ Test execution failed: {{error_msg}}", file=sys.stderr)
            os.makedirs("logs", exist_ok=True)
            error_screenshot = os.path.join("logs", "execution_failure.png")
            try:
                await page.screenshot(path=error_screenshot)
                print(f"📸 Error screenshot saved to {{error_screenshot}}")
            except Exception:
                pass
            await browser.close()
            print(f'JSON_RESULT: {{"status": "FAILED", "error": {{json.dumps(error_msg)}}}}')
            return False

if __name__ == "__main__":
    asyncio.run(run_tests())
'''

        try:
            response_text = await self.call_llm(
                prompt=prompt,
                system_instruction="You are a Senior Automation Engineer writing production-grade Playwright Python code.",
                model_name=self.config.GEMINI_FLASH_MODEL,
                mock_fallback=_mock_script_generator
            )

            script_code = ""
            if "```python" in response_text:
                script_code = response_text.split("```python")[1].split("```")[0].strip()
            elif "```" in response_text:
                script_code = response_text.split("```")[1].split("```")[0].strip()
            else:
                script_code = response_text.strip()

            if not script_code or "async_playwright" not in script_code:
                script_code = _mock_script_generator()

            state["current_script"] = script_code
            if "all_scripts" not in state or state["all_scripts"] is None:
                state["all_scripts"] = {}
            
            script_key = f"script_v{retry_count + 1}"
            state["all_scripts"][script_key] = script_code

            self.log_success(f"Generated Playwright test script ({len(script_code)} characters) as '{script_key}'")
            return state
        except Exception as e:
            self.log_error(f"Error during script generation: {e}")
            state["current_script"] = _mock_script_generator()
            return state
